### ISSUE TITLE
S1: As a Game Participant, I want to easily access the rules for each game mode at any time, so that I can quickly understand how to play without interrupting my gameplay experience.

### ISSUE THREAD

**Issue by steinerchristof** [sopra-fs24-group-15/server#1]
### Acceptance Criteria:

- [x] There is a button which is on every player’s screen to open the rulebook 
- [x] The rules are categorized by game mode (if multiple) 
- [x] There is a back button to get back to the correct screen where you opened the rules 

### Development Task:
- [x] sopra-fs24-group-15/client#1
- [x] sopra-fs24-group-15/client#2
- [x] sopra-fs24-group-15/client#73
- [x] sopra-fs24-group-15/client#84
- [x] #269
