### ISSUE TITLE
S2: As a user looking to play with friends, I want the ability to create a new lobby, so that we can enjoy playing together, enhancing our social gaming experience.

### ISSUE THREAD

**Issue by steinerchristof** [sopra-fs24-group-15/server#10]
### Acceptance Criteria: 

- [x] There is a create lobby button on the main menu. 
- [x] Each Lobby can have multiple participants but only one owner. 
- [x] A Lobby needs multiple players to continue. 
- [x] You can Join a Lobby with an automatically generated code. 

### Development Tasks: 

- [x] sopra-fs24-group-15/client#5
- [x] sopra-fs24-group-15/client#47
- [x] sopra-fs24-group-15/server#74
- [x] sopra-fs24-group-15/server#76
- [x] sopra-fs24-group-15/client#6
- [x] sopra-fs24-group-15/server#78
- [x] sopra-fs24-group-15/server#79
- [x] sopra-fs24-group-15/client#48
- [x] sopra-fs24-group-15/server#158
- [x] sopra-fs24-group-15/server#159
