### ISSUE TITLE
S12: Players should be able to select memes to download to their own library after each round. 

### ISSUE THREAD

**Issue by steinerchristof** [sopra-fs24-group-15/server#12]
### Acceptance Criteria

- [ ] At the end of each round, there is a button to save the created memes to your own library.
- [ ] After clicking the button, a player is able to select each of the memes.
- [ ] There is a button to select all of the memes at the same time.
- [ ] There is a button to confirm the selected memes and start the download to your own library.
- [ ] After the download, there is a popup screen showing if the download was successful or not.

### Development Tasks
- [x] sopra-fs24-group-15/client#32
- [x] sopra-fs24-group-15/client#33
- [x] sopra-fs24-group-15/client#34
- [x] sopra-fs24-group-15/client#35
- [x] sopra-fs24-group-15/server#135
- [x] sopra-fs24-group-15/server#136
