### ISSUE TITLE
S15: As a Player, I wish to join an existing public room, enabling me to engage in games with a broader community.

### ISSUE THREAD

**Issue by steinerchristof** [sopra-fs24-group-15/server#15]
### Acceptance Criteria
- [ ] Upon requesting to join, the lobby owner receives a notification or an alert with the player's name.
- [ ] Players whose requests are approved are automatically added to the room, with a success message displayed, including the lobby details and current participants.
- [x] If used the correct joincode player can join lobby that has not an active game
### Development Tasks
- [x] sopra-fs24-group-15/client#41
- [x] sopra-fs24-group-15/client#42
- [x] sopra-fs24-group-15/client#43
- [x] sopra-fs24-group-15/server#150
- [x] sopra-fs24-group-15/server#151
- [x] sopra-fs24-group-15/server#152
