### ISSUE TITLE
S16: As a Lobby Owner I want to be able to invite my friends by sending them a join option.

### ISSUE THREAD

**Issue by steinerchristof** [sopra-fs24-group-15/server#16]
### Acceptance Criteria
- [ ] A URL to join the Lobby is created.
- [x] The Owner can copy the Join code.
- [ ] By loading the URL you are automatically directed to the Lobby and can play the game.

### Development Tasks
- [x] sopra-fs24-group-15/client#44
- [x] sopra-fs24-group-15/client#45
- [x] sopra-fs24-group-15/server#155
- [x] sopra-fs24-group-15/server#156
- [x] sopra-fs24-group-15/server#157
