### ISSUE TITLE
S3: As a Lobby Owner, I aim to edit lobby settings and extensions to ensure the game suits our group's preferences and keeps all players informed.

### ISSUE THREAD

**Issue by steinerchristof** [sopra-fs24-group-15/server#2]
### Acceptance Criteria
- [ ] The Owner can Change the settings of a lobby (if any extensions are available). 
- [ ] The Users cannot change anything, but are still able to see the current settings. 

### Development Tasks
- [x] sopra-fs24-group-15/server#80
- [x] sopra-fs24-group-15/client#8
- [x] sopra-fs24-group-15/client#7
- [ ] sopra-fs24-group-15/server#83
- [x] sopra-fs24-group-15/server#84
- [x] sopra-fs24-group-15/client#9
