### ISSUE TITLE
S4: As a Lobbyowner, I want to ensure the game starts only with a minimum of 3 players, to maintain competitiveness and enjoyment. 

### ISSUE THREAD

**Issue by steinerchristof** [sopra-fs24-group-15/server#3]
### Acceptance Criteria
- [x] The game start button becomes active only when at least 3 players are present in the lobby. 
- [x] If attempted to start with fewer than 3 players, a message prompts the host to wait for more players. 
- [x] The players is visible to all users in the lobby. 

### Development Tasks
- [x] sopra-fs24-group-15/server#87
- [x] sopra-fs24-group-15/client#80
- [x] sopra-fs24-group-15/client#51
- [x] sopra-fs24-group-15/server#179
- [x] sopra-fs24-group-15/server#180
- [x] sopra-fs24-group-15/server#181
