### ISSUE TITLE
S6: As a Player, I desire to set up a username upon joining the game, ensuring I am recognizable to other participants.

### ISSUE THREAD

**Issue by steinerchristof** [sopra-fs24-group-15/server#5]
### Acceptance Criteria
- [x] A prompt for username creation appears when a player wants to join the game. 
- [x] The system checks for username uniqueness 
- [x] Other players in the lobby can see my chosen username. 

### Development Tasks
- [x] sopra-fs24-group-15/client#14
- [x] sopra-fs24-group-15/server#99
- [x] sopra-fs24-group-15/client#16
- [x] sopra-fs24-group-15/server#102
- [x] #160
- [x] #189 
- [x] #232
