### ISSUE TITLE
S7: When waiting in a lobby for the game to start, the player should be able to see the other users.

### ISSUE THREAD

**Issue by steinerchristof** [sopra-fs24-group-15/server#6]
### Acceptance Criteria
- [ ] While waiting in the lobby there should be a table where all the players which have already joined the lobby will be displayed. 
- [ ] The table should be updated continuously. A player's name disappears if he leaves the lobby and a new name appears if a new player joins the lobby. 

### Development Tasks
- [x] sopra-fs24-group-15/client#17
- [x] sopra-fs24-group-15/client#18
- [ ] sopra-fs24-group-15/server#107
- [x] sopra-fs24-group-15/server#108
- [x] sopra-fs24-group-15/server#109
- [x] #241
