### ISSUE TITLE
S8: As Game Participant, I want to be able to create a meme to a fixed topic using a image fetched from an API within a fixed time

### ISSUE THREAD

**Issue by steinerchristof** [sopra-fs24-group-15/server#7]
### Acceptance Criteria

- [ ] When starting a round of the game, the game should fetch a image from the API to all users screens. 
- [ ] The game also randomly chooses a topic from a list of predefined topics. 
- [ ] Participants should have a limited time to create their memes using the provided image.  
- [ ] A user can add text and customize the meme. 
- [ ] Once the time expires, the users should be prevented from making further edits to the meme. 

### Development Tasks

- [x] sopra-fs24-group-15/server#111
- [ ] sopra-fs24-group-15/client#20
- [x] sopra-fs24-group-15/client#21
- [ ] sopra-fs24-group-15/client#22
- [x] sopra-fs24-group-15/server#162
- [x] sopra-fs24-group-15/server#163
- [x] sopra-fs24-group-15/server#164
- [x] sopra-fs24-group-15/server#165
- [x] sopra-fs24-group-15/server#183
- [x] sopra-fs24-group-15/server#184 
- [x] sopra-fs24-group-15/client#49
- [x] sopra-fs24-group-15/client#50
- [x] sopra-fs24-group-15/server#201
- [x] sopra-fs24-group-15/server#202
- [x] sopra-fs24-group-15/server#207
- [x] sopra-fs24-group-15/server#208
- [x] sopra-fs24-group-15/server#212
- [x] sopra-fs24-group-15/server#211
- [x] sopra-fs24-group-15/server#219
- [ ] sopra-fs24-group-15/client#58
