### ISSUE TITLE
S9: As a User, I want to be able to see the current standing after each round of voting.

### ISSUE THREAD

**Issue by steinerchristof** [sopra-fs24-group-15/server#8]
### Acceptance Criteria
- [ ] After the voting process every Player should automatically be get a pop-up screen with the current score and the respective ranking. 
- [ ] Only the players in the current lobby should be able to see the ranking.
- [ ] After a fix set amount of time the pop-up should disappear and the game should continue.

### Development Tasks

- [ ] sopra-fs24-group-15/client#23
- [ ] sopra-fs24-group-15/client#24
- [x] sopra-fs24-group-15/client#62
- [ ] sopra-fs24-group-15/client#25
- [x] sopra-fs24-group-15/client#57
- [x] sopra-fs24-group-15/server#166
- [x] sopra-fs24-group-15/server#167
- [x] sopra-fs24-group-15/server#186
- [x] sopra-fs24-group-15/server#187
- [x] sopra-fs24-group-15/server#237
- [x] sopra-fs24-group-15/server#255
