### ISSUE TITLE
S10: As Game Participant, I want to be able to see the ranking screen at the end of the game, there I want to see my rank and the rank of all the other players. After a defined amount of time or after pressing a button I want to be redirected to the lobby.

### ISSUE THREAD

**Issue by steinerchristof** [sopra-fs24-group-15/server#9]
### Acceptance Criteria

- [x] The score and ranking of all the players in the lobby needs to be shown.  
- [ ] After a fix set amount of time the players need to be redirected back to the lobby. 
- [ ] All the players get redirected to the lobby and all the players that haven’t left should be able to play again from the lobby. 
- [x] There also needs to be a back to lobby button so the players can get to the lobby quicker.

### Development Tasks

- [x] sopra-fs24-group-15/client#26
- [x] sopra-fs24-group-15/client#27
- [x] sopra-fs24-group-15/client#28
- [x] sopra-fs24-group-15/client#29
- [x] sopra-fs24-group-15/server#122
- [x] sopra-fs24-group-15/server#123
- [x] sopra-fs24-group-15/server#124
- [x] sopra-fs24-group-15/server#125
